# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: "https"
  url: "dev-dataspaces.dit.upm.es"
  port: null

hosts_default: &hosts_default
  http: *http_host
  grpc: null
  graphql: null

api_version: &api_version "v1"

min_known_config: &min_known_config
  hosts: *hosts_default
  api_version: *api_version

is_catalog_datahub: &is_catalog_datahub false

common_config: &common_config
  hosts: *hosts_default
  db:
    db_type: Postgres
    url: "127.0.0.1"
    port: "1300"
  api:
    version: *api_version
    openapi_path: "/home/ging/rainbow/static/specs/openapi/auth/auth_consumer.json"
  is_local: false



# ==========================
# SSI AUTH
# ==========================
ssi_auth:
  common: *common_config
  wallet:
    api:
      protocol: "https"
      url: "wallet.demo.walt.id"
      port: null
    id: null
  client:
    class_id: "rainbow_consumer"
    display: null
  stuff_to_issue:
    vc_model: JwtVc
    w3c_data_model: V1
    dataspace_id: null
    federated_catalog_uri: null
  did_config:
    did: "did:jwk:eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiJ4T0F3WlpkQ3AwQ0dCQV9tMVVHR1VXcEM5THJlcmJjbDMxblJoZThzNzd6R204aXA3YUgtUW5NNUNLbEo1YXlvUDhKTV9rLWhVQ0V2Q09qNWw5VmNhN0RfNTdRMjRJUEtHN0dQSGdnYzZ5bGxwZFlnSkVlY2xUcXJGcjdGUFBxcThDQzY1WVpfS1hGY3ByOHJGRVFEUGtkc3gzbU1qTkYzQUpNNzBpaEItdGtOOWxxcHZLb0h6MzJRaHRybVhFY2t1X1NtVFlFTU9GVU0xd0I1TE4xNmN4ZzIxZXYwMnZGdlVCYmdWZENTNHZocjNHNlNMM2dPZXVzd3BZaTZtTTZ6clloY3lkaDJaRjZCUEZVMS1NNk9tcENGRnd6SFVWNTdqMHJMLUR0OU1Ja1FUWmxXam5kcVVOZG1Ecnlyd0E1OU8zS1lWYWY5cmUwdW9QS3ZGUmRmY3cifQ"
    type: Jwk
    did_web_options: null
    #    domain: "CHANGE_ME"
    #    path: null
  requirements_to_verify:
    is_cert_allowed: false
    vcs_requested: [ ]
  gaia_active: false

