# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: 'http'
  url: '127.0.0.1'
  port: '1200'

hosts_default: &hosts_default
  http: *http_host
  grpc: null
  graphql: null

api_version: &api_version 'v1'

min_known_config: &min_known_config
  hosts: *hosts_default
  api_version: *api_version

is_catalog_datahub: &is_catalog_datahub false

policy_templates_folder: &policy_templates_folder '../static/policy_templates/'

cache_config: &cache_config
  cache_type: Redis
  url: '127.0.0.1'
  port: '6379'
  user: 'default'
  password: 'ds_core_provider_redis'

common_config: &common_config
  hosts: *hosts_default
  db:
    db_type: Postgres
    url: '127.0.0.1'
    port: '1400'
  api:
    version: *api_version
    openapi_path: '../static/specs/openapi/auth/auth_provider.json'
  keys_path: '../static/certificates/provider/'
  is_local: true

# ==========================
# MONOLITH
# ==========================
monolith:
  common: *common_config
  cache: *cache_config

# ==========================
# CATALOG
# ==========================
catalog:
  common: *common_config
  cache: *cache_config
  is_datahub: *is_catalog_datahub
  policy_templates_folder: *policy_templates_folder
  datahub_host: null
  datahub_token: null
  ssi_auth: *min_known_config
  contracts: *min_known_config

# ==========================
# SSI AUTH
# ==========================
ssi_auth:
  common_config: *common_config
  wallet_config:
    api:
      protocol: 'http'
      url: '127.0.0.1'
      port: '7001'
    id: null
  client_config:
    class_id: 'rainbow_consumer'
    display: null
  vc_config:
    vc_model: JwtVc
    w3c_data_model: V1
  verify_req_config:
    is_cert_allowed: false
    vcs_requested: [DataspaceParticipant]
  gaia_config: null
  did_config:
    did: 'did:jwk:eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiIwLW5uempxdDNQVXZtMUVPaEVxNUNxQ05WcEVUM3I4S0Y3VWRKSDJlRFV1dDNhSFlFWGFxbG51SXZ4TUVmN0J1dkhMVnlUaW95U1BoMV9TaDF0ZnBwdF9aNXpXU1ZZUGp0ekZ0QlJsQ0pQYzNfc2YtelRIQURMMmNyYW84WmxXa1FFR2ZtX1g3Y2QtMkd5bmVuR0k0a01rLU9vRERUWEJNRmVoOVdtR1dyMGZBeHJ4Qkp3Unh4QTExODNIOWo1QkY3dlpVZ0Y3akYzV28xcVlva0Z4emJ0Q2FhWWkzTmE3aFYtWWRIYkg3QUhkYnlJa1JvTHhhVG9tb3ktRHRmb0dSSGRzTmpzNDFqZUwxTG5XczJENnVJMm43QTBFQ1hIaHJjZTlMbkt6eXNMWktRM3Ffa2hxR0UzRTZJT1djajRMT1NvNGJ4SXktZzNVT0NpeElSelJ2bFEifQ'
    type: Jwk
    did_web_options: null
    #    domain: "CHANGE_ME"
    #    path: null

# ==========================
# CONTRACTS
# ==========================
contracts:
  common: *common_config
  ssi_auth: *min_known_config
  is_catalog_datahub: *is_catalog_datahub

# ==========================
# TRANSFER
# ==========================
transfer:
  common: *common_config
  contracts: *min_known_config
  catalog: *min_known_config
  ssi_auth: *min_known_config
  is_catalog_datahub: *is_catalog_datahub

# ==========================
# GATEWAY
# ==========================
gateway:
  common: *common_config
  is_production: false
  transfer: *min_known_config
  contracts: *min_known_config
  catalog: *min_known_config
  ssi_auth: *min_known_config
  is_catalog_datahub: *is_catalog_datahub
