# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: "http"
  url: "127.0.0.1"
  port: "1100"

hosts_default: &hosts_default
  http: *http_host
  grpc: null
  graphql: null

api_version: &api_version "v1"

min_known_config: &min_known_config
  hosts: *hosts_default
  api_version: *api_version

is_catalog_datahub: &is_catalog_datahub false

policy_templates_folder: &policy_templates_folder "../static/policy_templates"

cache_config: &cache_config
  cache_type: Redis
  url: "127.0.0.1"
  port: "6380"
  user: "default"
  password: "ds_core_consumer_redis"

common_config: &common_config
  hosts: *hosts_default
  db:
    db_type: Postgres
    url: "127.0.0.1"
    port: "1300"
  api:
    version: *api_version
    openapi_path: "../static/specs/openapi/auth/auth_consumer.json"
  is_local: true

# ==========================
# MONOLITH
# ==========================
monolith:
  common: *common_config
  cache: *cache_config

# ==========================
# CATALOG
# ==========================
catalog:
  common: *common_config
  cache: *cache_config
  is_datahub: *is_catalog_datahub
  policy_templates_folder: *policy_templates_folder
  datahub_host: null
  datahub_token: null
  ssi_auth: *min_known_config
  contracts: *min_known_config

# ==========================
# SSI AUTH
# ==========================
ssi_auth:
  common_config: *common_config
  wallet:
    api:
      protocol: "http"
      url: "127.0.0.1"
      port: "7001"
    id: null
  client_config:
    class_id: "rainbow_consumer"
    display: null
  gaia_active: false
  vc_config:
    vc_model: JwtVc
    w3c_data_model: V1
    dataspace_id: null
    federated_catalog_uri: null
  verify_req_config:
    is_cert_allowed: false
    vcs_requested: [ ]
  did_config:
    did: "did:jwk:eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiJ4T0F3WlpkQ3AwQ0dCQV9tMVVHR1VXcEM5THJlcmJjbDMxblJoZThzNzd6R204aXA3YUgtUW5NNUNLbEo1YXlvUDhKTV9rLWhVQ0V2Q09qNWw5VmNhN0RfNTdRMjRJUEtHN0dQSGdnYzZ5bGxwZFlnSkVlY2xUcXJGcjdGUFBxcThDQzY1WVpfS1hGY3ByOHJGRVFEUGtkc3gzbU1qTkYzQUpNNzBpaEItdGtOOWxxcHZLb0h6MzJRaHRybVhFY2t1X1NtVFlFTU9GVU0xd0I1TE4xNmN4ZzIxZXYwMnZGdlVCYmdWZENTNHZocjNHNlNMM2dPZXVzd3BZaTZtTTZ6clloY3lkaDJaRjZCUEZVMS1NNk9tcENGRnd6SFVWNTdqMHJMLUR0OU1Ja1FUWmxXam5kcVVOZG1Ecnlyd0E1OU8zS1lWYWY5cmUwdW9QS3ZGUmRmY3cifQ"
    type: Jwk
    did_web_options: null
    #    domain: "CHANGE_ME"
    #    path: null

# ==========================
# CONTRACTS
# ==========================
contracts:
  common: *common_config
  ssi_auth: *min_known_config
  is_catalog_datahub: *is_catalog_datahub

# ==========================
# TRANSFER
# ==========================
transfer:
  common: *common_config
  contracts: *min_known_config
  catalog: *min_known_config
  ssi_auth: *min_known_config
  is_catalog_datahub: *is_catalog_datahub

# ==========================
# GATEWAY
# ==========================
gateway:
  common: *common_config
  is_production: false
  transfer: *min_known_config
  contracts: *min_known_config
  catalog: *min_known_config
  ssi_auth: *min_known_config
  is_catalog_datahub: *is_catalog_datahub

